# Generated by Django 2.2.5 on 2019-09-03 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'RestAPI_user',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=3, verbose_name='type')),
                ('stock_symbol', models.CharField(max_length=10, verbose_name='stock_symbol')),
                ('stock_quantity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)], verbose_name='shares')),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(130.42), django.core.validators.MaxValueValidator(195.65)], verbose_name='price')),
                ('trade_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_trades', to='RestAPI.User')),
            ],
            options={
                'verbose_name': 'trade',
                'db_table': 'RestAPI_trade',
            },
        ),
    ]
